export const CREATE_ASSET = "CREATE_ASSET";
export const RETRIEVE_ASSETS = "RETRIEVE_ASSETS";
export const RETRIEVE_ALL_ASSETS = "RETRIEVE_ALL_ASSETS";
export const UPDATE_ASSET = "UPDATE_ASSET";
export const DELETE_ASSET = "DELETE_ASSET";
export const DELETE_ALL_ASSETS = "DELETE_ALL_ASSETS";