export const YOU_SUBMITTED_SUCCESSFULLY = 'You submitted successfully!';
export const ADD = 'Add';
export const SUBMIT = 'Submit';
export const DELETE = 'Delete';
export const UPDATE = 'Update'
export const ASSET = 'Asset';
export const REMOVE_ALL = 'Remove All';
export const NAME = 'Name'
export const DESC = 'Description';
export const EDIT = 'Edit';
export const ASSET_LIST = 'Assets List';
export const SEARCH = 'Search';